filename <- readline("CSV file: ")
data <- read.csv(filename)
number <- nrow(data)
shortest <- min(data$time)
longest <- max(data$time)
total <- sum(data$time)
print(number)
print(shortest)
print(longest)
print(total)
